
server:
  port: 0

spring:
  application:
    name: bonusservice
  ### ??????????
  profiles:
    active: dev
  ### ??????????
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\\Users\\Daglemino\\Documents\\db\\bonus.db
    username:
    password:


  ### sqlite??????????
  jpa:
    database-platform: at.technikumwien.bonus.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka