
server:
  port: 0

spring:
  application:
    name: statservice
  profiles:
    active: dev
  ### Kafka configuration :
  cloud:
    stream:
      bindings:
        input:
          destination: travelportal.readers
          content-type: application/json
          group: travelportal.readers.statgroup
      kafka:
        binder:
          brokers: localhost:9092

  ### JPA - Sqlite
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\\Users\\Oliver\\Documents\\db\\stat.db
    username:
    password:
  jpa:
    database-platform: at.technikumwien.stat.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka