server:
  port: 0

spring:
  application:
    name: blogservice
  profiles:
    active: dev
  ### Kafka configurations:
  cloud:
    stream:
      bindings:
        output:
          destination: travelportal.readers
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

  ### JPA - Sqlite
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\\Users\\Oliver\\Documents\\db\\blog.db
    username:
    password:
  jpa:
    database-platform: at.technikumwien.blog.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka