
server:
  port: 7500

spring:
  application:
    name: blogservice
  ### ??????????
  profiles:
    active: dev
  ### ??????????
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\\Users\\Daglemino\\Documents\\db\\springboot.db
    username:
    password:
  ### sqlite??????????
  jpa:
    database-platform: at.technikumwien.blog.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka