server:
  port: 5555

spring:
  application:
    name: travelgateway

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  retryableStatusCodes: 404, 500
  ReadTimeout: 60000

zuul:
  prefix: /api
  routes:
    blogservice: /blog/**
    bonusservice: /bonus/**
    statservice: /stat/**
  retryable: true
  ignored-services: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 444000