server:
  port: 5555

spring:
  application:
    name: travelgateway

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  retryableStatusCodes: 404, 500

zuul:
  prefix: /api
  routes:
    blogpostservice: /blog/**
    bonusservice: /bonus/**
    statisticsservice: /stats/**
  retryable: true